name: "Ci app-multiselect-demo"

on:
    push:
      branchs:
       - main

jobs:
  deploy:
   runs-on: ununtu-latest
   strategy:
        matrix:
          node-version: [16.x]
   steps:
      - uses: actions/checkout@v3
      - name: Using Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}}
      - name: Install and run lint
        run: |
          yarn install
          yarn lint
