name: "Ci app-multiselect-demo"

on:
  push:
    branches:
      - main

jobs:
  lint:
   runs-on: ubuntu-latest
   strategy:
        matrix:
          node-version: [16.x]
   steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and run lint
        run: |
          yarn install
          yarn lint

  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and run test
        run: |
          yarn install
          yarn test
